### ISSUE TITLE
FSharpCompletionProvider throws MissingMethodException in Visual Studio 2017 Update 3 Preview

### ISSUE THREAD

**Issue by pkanavos** [Microsoft/visualfsharp#3067]
FSharpCompletionProvider throws a TypeInitializationException with an inner MissingMethodException when used in Visual Studio 2017 Update 3 Preview

    System.TypeInitializationException: The type initializer for `Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionProvider` threw an exception. 
    ---> System.TypeInitializationException: The type initializer for `<StartupCode$FSharp-Editor>.$CompletionProvider` threw an exception. 
    ---> System.MissingMethodException: Method not found: 
    Microsoft.CodeAnalysis.Completion.CompletionItem Microsoft.CodeAnalysis.CompletionCommonCompletionItem.Create.(System.String, System.Nullable`1<Microsoft.CodeAnalysis.Glyph>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.SymbolDisplayPart>, System.String, System.String, System.Nullable`1<Int32>, Boolean, Boolean, System.Collections.Immutable.ImmutableDictionary`2<System.String,System.String>, System.Collections.Immutable.ImmutableArray`1<System.String>, Microsoft.CodeAnalysis.Completion.CompletionItemRules)`.`

The reason is that the method call [here](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Completion/CompletionProvider.fs#L50) doesn't have the second `CompletionRules` parameter defined [here](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Completion/CommonCompletionItem.cs#L11)

FSharpCompletionProvider uses:

    CommonCompletionItem.Create(keyword, Nullable Glyph.Keyword, sortText = sprintf "%06d" (1000000 + n))

The method is defined as :

    public static CompletionItem Create(
            string displayText,
            CompletionItemRules rules,
            Glyph? glyph = null,
            ImmutableArray<SymbolDisplayPart> description = default(ImmutableArray<SymbolDisplayPart>),
            string sortText = null,
            string filterText = null,
            bool showsWarningIcon = false,
            ImmutableDictionary<string, string> properties = null,
            ImmutableArray<string> tags = default(ImmutableArray<string>))

Clearly, the second required parameter is missing.

The exception shows a different signature, with the CompletionItemRules parameter appearing as an optional at the end. This suggests that FSharpCompletionProvider was compiled against a different version of Roslyn.

Disabling completion from Options > F# > Intellisense > Completion doesn't prevent the exceptions.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a new F# Console Project

2. Open Program.fs and press `Ctrl + Space` to run autocompletion. 

#### Expected behavior

Either a set of suggestions or nothing

#### Actual behavior

Exception box saying that `The type initializer for 'Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionProvider' threw an exception.`

#### Related information 

* OS        : Windows 10
* NET       : 4.7
* Editor    : Visual Studio 2017 Update 3 Preview
* Branch  : Visual F# Tools Nightly build 15.4.1.17051605
* Severity: Severe. Unable to use VS 15.3 to edit F# projects due to the exception boxes shown each time Space, Del, Tab or Backspace are pressed

Full Exception from ActivityLog.xml :

	System.TypeInitializationException: The type initializer for `Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionProvider` threw an exception. ---> System.TypeInitializationException: The type initializer for `<StartupCode$FSharp-Editor>.$CompletionProvider` threw an exception. ---> System.MissingMethodException: Method not found: `Microsoft.CodeAnalysis.Completion.CompletionItem Microsoft.CodeAnalysis.Completion.CommonCompletionItem.Create(System.String, System.Nullable`1<Microsoft.CodeAnalysis.Glyph>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.SymbolDisplayPart>, System.String, System.String, System.Nullable`1<Int32>, Boolean, Boolean, System.Collections.Immutable.ImmutableDictionary`2<System.String,System.String>, System.Collections.Immutable.ImmutableArray`1<System.String>, Microsoft.CodeAnalysis.Completion.CompletionItemRules)`.
	   at <StartupCode$FSharp-Editor>.$CompletionProvider.-cctor@47-1.Invoke(Int32 n, Tuple`2 tupledArg)
	   at Microsoft.FSharp.Primitives.Basics.List.mapi[T,TResult](FSharpFunc`2 f, FSharpList`1 x)
	   at Microsoft.FSharp.Collections.ListModule.MapIndexed[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list)
	   at <StartupCode$FSharp-Editor>.$CompletionProvider..cctor()
	   --- End of inner exception stack trace ---
	   at Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionProvider..cctor()
	   --- End of inner exception stack trace ---
	   at Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionProvider..ctor(Workspace workspace, SVsServiceProvider serviceProvider, FSharpCheckerProvider checkerProvider, ProjectInfoManager projectInfoManager, AssemblyContentProvider assemblyContentProvider)
	   at Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionService..ctor(Workspace workspace, SVsServiceProvider serviceProvider, FSharpCheckerProvider checkerProvider, ProjectInfoManager projectInfoManager, AssemblyContentProvider assemblyContentProvider)
	   at Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionServiceFactory.Microsoft-CodeAnalysis-Host-Mef-ILanguageServiceFactory-CreateLanguageService(HostLanguageServices hostLanguageServices)
	   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.<>c__DisplayClass4_0.<.ctor>b__1()
	   at System.Lazy`1.CreateValue()
	   at System.Lazy`1.LazyInitValue()
	   at System.Lazy`1.get_Value()
	   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.GetService[TLanguageService]()
	   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.GetCompletionService()
	   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler)
	   at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.ExecuteCommandWorker[TCommandArgs](TCommandArgs args, Action nextHandler)
	   at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler)
	   at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.<>c__DisplayClass6_1`1.<ExecuteHandlers>b__1()
	   at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteReturnOrTypeCommand(CommandArgs args, Action nextHandler, CancellationToken cancellationToken)
	   at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler)
	   at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.<>c__DisplayClass6_1`1.<ExecuteHandlers>b__1()
	   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.HandlePossibleTypingCommand(CommandArgs args, Action nextHandler, Action`1 actionIfInsideActiveSpan)
	   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler)
	   at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.<>c__DisplayClass6_1`1.<ExecuteHandlers>b__1()
	   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler)
	   at Microsoft.CodeAnalysis.Editor.CommandHandlers.SignatureHelpCommandHandler.ExecuteCommandWorker[TCommandArgs](TCommandArgs args, Action nextHandler)
	   at Microsoft.CodeAnalysis.Editor.CommandHandlers.SignatureHelpCommandHandler.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler)
	   at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.ExecuteHandlers[T](IList`1 commandHandlers, T args, Action lastHandler)
	   at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.Microsoft.CodeAnalysis.Editor.ICommandHandlerService.Execute[T](IContentType contentType, T args, Action lastHandler)
	   at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.ExecuteTypeCharacter(IntPtr pvaIn, ITextBuffer subjectBuffer, IContentType contentType, Action executeNextCommandTarget)
	   at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.ExecuteVisualStudio2000(Guid&amp; pguidCmdGroup, UInt32 commandId, UInt32 executeInformation, IntPtr pvaIn, IntPtr pvaOut, ITextBuffer subjectBuffer, IContentType contentType)
	   at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.Exec(Guid&amp; pguidCmdGroup, UInt32 commandId, UInt32 executeInformation, IntPtr pvaIn, IntPtr pvaOut)
	   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
	   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
	   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
	   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
	   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
	   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)
	   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()
	   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

**Comment by vasily-kirichenko** [comment]
See https://github.com/Microsoft/visualfsharp/issues/3042

**Comment by pkanavos** [comment]
@vasily-kirichenko I have no problems with 15.2

**Comment by vasily-kirichenko** [comment]
Me either. I mean it seems they updated Microsoft.CodeAnalysis.XXX assemblies in 15.3. We must do the same in the version that will go to 15.3 release. /cc @brettfo

**Comment by cartermp** [comment]
#3042 is a related issue.  There's actually no difference in the F# tools from 15.2 and 15.3 Preview 1.  Both are released at the same time, hence this issue.  @brettfo is working on this and a few others ([as specified in the Release Notes](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes#a-idknownissues-aknown-issues)).  This is another case of us being bitten by InternalsVisibleTo because an internal API changed.  This is a big one to address for the greater Roslyn team (TypeScript suffers these sorts of issues as well), but there is unlikely to be work done for it until .NET Core 2.0 ships.

**Comment by cartermp** [comment]
Current target is 15.3 Update 2, which should land alongside .NET Core 2.0 support and project system support.  I should create an announcement issue.

**Comment by dsyme** [comment]
@cartermp This is fixed by https://github.com/Microsoft/visualfsharp/pull/3106, correct?

**Comment by cartermp** [comment]
@dsyme Not sure.  AFAIK a change is still needed in FSharp.Editor to call the right overload.  @brettfo had that on his list as of Friday.  I've been out of town since Saturday though, so I'm not sure if that's been completed.

**Comment by cartermp** [comment]
Assigning @brettfo here just for completeness so it matches our dupe of this in VSTS for shiproom.

**Comment by ridecar2** [comment]
I'm still having this issue whenever I try to activate autocomplete.

**Comment by dsyme** [comment]
> Assigning @brettfo here just for completeness so it matches our dupe of this in VSTS for shiproom.

@brettfo where are we with this one?  Thanks

**Comment by brettfo** [comment]
The code currently in `master` (which is what builds to our nightly VSIX channel) will only work on 15.2 builds of Visual Studio.  The `vs2017-rtm` branch (which doesn't build to any VSIX channel) will work against 15.3 preview builds of VS.

The current recommendation is to either:
-  Use 15.2 build of VS with or without nightlies.
-  Use 15.3 preview build of VS _without_ nightlies.

Once we've shipped the RTW of 15.3 then all references will be updated to use 15.3 Roslyn binaries.

**Comment by dsyme** [comment]
@brettfo OK, thanks.  

* So post 15.3 nightlies will only work if you have 15.3 installed?  Is there a way we can condition the nightly so it doesn't install into 15.2?

* Could you advise me on #3071? This requires 15.3 binaries (or we need to validate it against 15.3 binaries, and put a hack in to make sure it doesn't activate against 15.2.  If we can assume 15.3 binaries then all the better,

**Comment by cartermp** [comment]
Closing, as this is now fixed.

**Comment by Titaye** [comment]
Issue seems to appear again with nightly version VisualFSharp.15.4.1.17072401 and VisualFSharp.15.4.1.17072102 on VS 15.3.0 preview 5.0

```System.TypeInitializationException: The type initializer for 'Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionProvider' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-Editor>.$CompletionProvider' threw an exception. ---> System.MissingMethodException: Method not found: 'Microsoft.CodeAnalysis.Completion.CompletionItem Microsoft.CodeAnalysis.Completion.CommonCompletionItem.Create(System.String, System.Nullable`1<Microsoft.CodeAnalysis.Glyph>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.SymbolDisplayPart>, System.String, System.String, System.Nullable`1<Int32>, Boolean, Boolean, System.Collections.Immutable.ImmutableDictionary`2<System.String,System.String>, System.Collections.Immutable.ImmutableArray`1<System.String>, Microsoft.CodeAnalysis.Completion.CompletionItemRules)'. at <StartupCode$FSharp-Editor>.$CompletionProvider.-cctor@49-1.Invoke(Int32 n, Tuple`2 tupledArg) at Microsoft.FSharp.Primitives.Basics.List.mapi[T,TResult](FSharpFunc`2 f, FSharpList`1 x) at Microsoft.FSharp.Collections.ListModule.MapIndexed[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) at <StartupCode$FSharp-Editor>.$CompletionProvider..cctor() --- End of inner exception stack trace --- at Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionProvider..cctor() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of inner exception stack trace --- at Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionProvider..ctor(Workspace workspace, SVsServiceProvider serviceProvider, FSharpCheckerProvider checkerProvider, ProjectInfoManager projectInfoManager, AssemblyContentProvider assemblyContentProvider) at Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionService..ctor(Workspace workspace, SVsServiceProvider serviceProvider, FSharpCheckerProvider checkerProvider, ProjectInfoManager projectInfoManager, AssemblyContentProvider assemblyContentProvider) at Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionServiceFactory.Microsoft-CodeAnalysis-Host-Mef-ILanguageServiceFactory-CreateLanguageService(HostLanguageServices hostLanguageServices) at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.<>c__DisplayClass4_0.<.ctor>b__1() at System.Lazy`1.CreateValue() at System.Lazy`1.LazyInitValue() at System.Lazy`1.get_Value() at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.GetService[TLanguageService]() at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.GetCompletionService() at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.ExecuteCommandWorker[TCommandArgs](TCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.<>c__DisplayClass6_1`1.<ExecuteHandlers>b__1() at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteReturnOrTypeCommand(CommandArgs args, Action nextHandler, CancellationToken cancellationToken) at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.<>c__DisplayClass6_1`1.<ExecuteHandlers>b__1() at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.HandlePossibleTypingCommand(CommandArgs args, Action nextHandler, Action`1 actionIfInsideActiveSpan) at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.<>c__DisplayClass6_1`1.<ExecuteHandlers>b__1() at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.CommandHandlers.SignatureHelpCommandHandler.ExecuteCommandWorker[TCommandArgs](TCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.CommandHandlers.SignatureHelpCommandHandler.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.ExecuteHandlers[T](IList`1 commandHandlers, T args, Action lastHandler) at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.Microsoft.CodeAnalysis.Editor.ICommandHandlerService.Execute[T](IContentType contentType, T args, Action lastHandler) at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.ExecuteTypeCharacter(IntPtr pvaIn, ITextBuffer subjectBuffer, IContentType contentType, Action executeNextCommandTarget) at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.ExecuteVisualStudio2000(Guid& pguidCmdGroup, UInt32 commandId, UInt32 executeInformation, IntPtr pvaIn, IntPtr pvaOut, ITextBuffer subjectBuffer, IContentType contentType) at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 commandId, UInt32 executeInformation, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)```

**Comment by dsyme** [comment]
@Titaye 
> Issue seems to appear again with nightly version VisualFSharp.15.4.1.17072401 and VisualFSharp.15.4.1.17072102 on VS 15.3.0 preview 5.0

As mentioned above, the nightlies should not be used with 15.3.  Only use them with 15.2

**Comment by Titaye** [comment]
Ok sorry, I've undestood the oposite. Thanks
