### ISSUE TITLE
Cannot build F# .NET Standard project when referenced from C# .NET Core project

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#5640]
Using VS 15.8.4:

1. Create a new .NET Standard F# library
2. Create a new .NET Core C# console app
3. Add a reference from the console app to the library
4. Build.

Two errors:

`MSB4064 The "EmbeddedFiles" parameter is not supported by the "Fsc" task. Verify the parameter exists on the task, and it is a settable public instance property.`

`MSB4063 The "Fsc" task could not be initialized with its input parameters.`

![image](https://user-images.githubusercontent.com/6309070/45503541-008d9680-b73c-11e8-9d59-b24e31ffa63e.png)

**Comment by cartermp** [comment]
cc @KevinRansom

**Comment by cartermp** [comment]
Is this related to #4075?

**Comment by KevinRansom** [comment]
@phillip, I tried this on my work machine it works fine; ans also I tried it on a clean VM and it works fine.

I think you may have environmental issues.

**Comment by cartermp** [comment]
Yep, this seems like it was environmental. I had a bunch of SDKs on my machine, multiple previews, and other various weird things with my VS install that may have resulted in the wrong SDK being picked up. With a fresh install, it's all golden.

**Comment by irium** [comment]
@cartermp Upping the issue. Maybe open new issue for my problem?

**Comment by KevinRansom** [comment]
So … 

this is is the cause:  https://github.com/Microsoft/visualfsharp/blame/89275d2ce1ec3953d737017a8be087c2579259f3/src/fsharp/FSharp.Build/Fsc.fs#L295

The buildtask property for Embedded Source files was renamed from Embed to EmbeddedFiles.  The corresponding Microsoft.NetSdk.targets and Microsoft.FSharp.Targets file were updated at the same time.  The error would seem to indicate that a mismatched set of targets and buildtask are in use.

Could you please set the build verbosity to diagnostic, and build the project within VS, and copy and paste the results to a text file and attach the file to this issue, and I can see if I can figure out why.

Thanks

Kevin

**Comment by irium** [comment]
[build.zip](https://github.com/Microsoft/visualfsharp/files/2412270/build.zip)

@cartermp That's a very big file.

**Comment by KevinRansom** [comment]
@irium yes it is.

**Comment by irium** [comment]
Hmm, now after updating Visual studio to 15.8.5 and installing latest nightly the behavior is strange:
after full clean the build (Rebuild solution) is failing with the errors as above. But if build again after this (not rebuild, just regular `Ctrl+Shift+B`) then the build succeeds.

**Comment by KevinRansom** [comment]
There isn't really much that we can do about this.  It seems to occur because msbuild processes are cached, and shared between instances of visual studio.  Which seems a bit wierd to me ...

In order to repro this I had to:  
1. Install RTM VS 2017.8.5
2. Install a VS2017 preview
3. Add the F# nightly to the VS2017.8.5 RTM
4. Open the VS2017 preview, build an F# project
5. Open the VS2017.8.5 RTM
6. Open and try to build the F# project

This wierdness gave me a reliable repro.
The fix was to type the following command in an administrator command window:
taskkill /f /im msbuild.exe

**An explanation,**
It seems that VS reuses the msbuild instance even between differing versions of Visual Studio.  Personally, I think this is a fairly dubious idea.  Anyway doing a taskkill on msbuild.exe seems to fix everything.


I hope this helps,

Kevin

**Comment by irium** [comment]
@KevinRansom Hmm, I have no VS2017 Preview installed. All my mentioned builds was executed in the same VS2017 Pro instance.

**Comment by 0x53A** [comment]
Can you try to set the environment variable ``MSBUILDDISABLENODEREUSE`` to ``1``?

Then reboot, to make sure it is actually applied.

This will globally disable the node reuse _feature_.

If you want, you can delete the env var again afterwards, but I always set it first thing after installing VS, got burnt too often ...

**Comment by cartermp** [comment]
Closing as an underlying root bug is being fixed in 15.8.6, and the F# component to this is solved with #5700. When 15.8.6 is released, the F# nightly feed should have the full fix.

**Comment by chadunit** [comment]
I am getting the two errors in the OP intermittently with VS 15.9.4 and F# nightly 15.8.20181217.1.

The comments above suggest it should be fixed in 15.8.6 and the nightlies, is that no longer the case?

I made sure also to delete the .vs folder as mentioned in the link [above](https://github.com/Microsoft/visualfsharp/issues/5640#issuecomment-424430609) but the issue still reoccurs.

The errors get cleared by killing msbuild.exe but eventually reoccur.

Is there more to come regarding a fix in 16.0 or is there potentially another issue?

**Comment by majocha** [comment]
Yes, I'm seeing this from time to time, too.

**Comment by majocha** [comment]
@cartermp tested now and couldn't reproduce with nightly uninstalled. However I reinstalled nightly and can't repro at all, so it's kind of random.

**Comment by chadunit** [comment]
With the nightly installed, I can generally repro a transient/recoverable occurrence of the error by adding a nuget reference to Microsoft.EntityFrameworkCore to a F# .NET Core class library. After producing the error upon package install, it still builds successfully and then clears the error. (I've also experienced a persistent version of the error where the build fails until doing the msbuild kill but don't know how to repro that on demand.)

With nightly uninstalled, I cannot repro the above recoverable error. I will run without nightly for a while to see if it occurs at all.

**Comment by majocha** [comment]
Another PC, nightly 1217.1:
new netstandard project, everything is fine. After updating FSharp.Core nuget from 4.5.2 to 4.5.4 the two errors show up on the list immediately. Project builds fine and errors disappear after build.
